services:
  # Serviço do Backend Laravel (PHP)
  laravel_app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: gemini_laravel_app
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network

  # Serviço do Servidor Web (Nginx)
  nginx:
    image: nginx:1.25-alpine
    container_name: gemini_nginx
    restart: unless-stopped
    ports:
      - "8080:80" # Acessível em http://localhost:8080 na sua máquina
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel_app
    networks:
      - app-network

  # Serviço do Frontend (Vue.js com Vite)
  vue_frontend:
    image: node:20-alpine  # Alterado para versão 20 (LTS atual)
    container_name: gemini_vue_frontend
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - app-network

# Define a rede que os contêineres usarão para se comunicar
networks:
  app-network:
    driver: bridge